<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<AssemblyName>PLSignals.MP</AssemblyName>
		<TargetFramework>net48</TargetFramework>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
		<WarningsAsErrors>CS8600;CS8602;CS8603</WarningsAsErrors>
	</PropertyGroup>

	<!-- PL Signals -->
	<ItemGroup>
		<ProjectReference Include="..\PLSignals.Game\PLSignals.Game.csproj"/>
	</ItemGroup>

	<!-- DV Signals -->
	<ItemGroup>
		<Reference Include="Signals.Game"/>
	</ItemGroup>

	<!-- Multiplayer -->
	<ItemGroup>
		<Reference Include="MultiplayerAPI"/>
	</ItemGroup>

	<!-- Unity -->
	<ItemGroup>
		<Reference Include="UnityEngine"/>
		<Reference Include="UnityEngine.CoreModule"/>
	</ItemGroup>

	<!-- Mod Loader -->
	<ItemGroup>
		<PackageReference Include="UnityModManager" Version="0.27.2"/>
	</ItemGroup>

	<!-- Null Checking -->
	<ItemGroup>
		<PackageReference Include="Nullable" Version="1.3.1" PrivateAssets="all"/>
	</ItemGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<!-- Copy to build folder -->
		<Copy SourceFiles="$(TargetPath)" DestinationFolder="../build/"/>
	</Target>
</Project>